### PR TITLE
Hamburger Icon, small enhancements

### PR DESCRIPTION
**Pull request by carstene1ns**
- Responsive menu
- css/js is combined, compressed and hashed now
- scss is split in import modules
- doc update
- added typografy enhancements

### CODE REVIEW

**Comment by carstene1ns** [comment]
https://deploy-preview-82--easyrpg.netlify.app/ <- be sure to scale screen under 700px wide.

**Review by fdelapena — APPROVED** [review]
Tested and looks good to me, only thing not sure if on purpose: touchable zone is just the text, otherwise adding some `text-align:center` and `width: 97%` (or `97vw`) or similar should do the trick (or using `display: table-cell`).

**Comment by carstene1ns** [comment]
Good idea, will add later.

Apropos, we could use something different than hamburger, e.g.

icons

Initially thought about animated trisquel, but some might not see this as menu icon then...

**Comment by carstene1ns** [comment]
Updated description. This one is ready.

**Pull request merged**
