### PR TITLE
Add some tools and snapcraft package

### PR DESCRIPTION
**Pull request by carstene1ns**

### CODE REVIEW

**Comment by Ghabry** [comment]
jenkins: test this please

**Review by Ghabry — APPROVED** [review]
well guess that error is normal because of the other PR that installs new stuff.
Tested it locally. Works fine.

**Comment by carstene1ns** [comment]
Yep, I updated the PR builder to use the Makefile already.

**Comment by carstene1ns** [comment]
jenkins: test this please

**Comment by carstene1ns** [comment]
meh, `lcfstrings.exe: 404`

**Comment by Ghabry** [comment]
jenkins: test this please

**Pull request merged**
